/*
 * Brisk
 *
 * Cross-platform application framework
 * --------------------------------------------------------------
 *
 * Copyright (C) 2024 Brisk Developers
 *
 * This file is part of the Brisk library.
 *
 * Brisk is dual-licensed under the GNU General Public License, version 2 (GPL-2.0+),
 * and a commercial license. You may use, modify, and distribute this software under
 * the terms of the GPL-2.0+ license if you comply with its conditions.
 *
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <http://www.gnu.org/licenses/>.
 *
 * If you do not wish to be bound by the GPL-2.0+ license, you must purchase a commercial
 * license. For commercial licensing options, please visit: https://brisklib.com
 */
#pragma once

#include <string_view>

constexpr std::string_view helloWorld[] = {
    "Hello Wêreld!",
    "Përshendetje Botë!",
    "ሰላም ልዑል!",
    "مرحبا بالعالم!",
    "Բարեւ աշխարհ!",
    "Kaixo Mundua!",
    "Прывітанне Сусвет!",
    "ওহে বিশ্ব!",
    "Здравей свят!",
    "Hola món!",
    "Moni Dziko Lapansi!",
    "你好世界！",
    "Pozdrav svijete!",
    "Ahoj světe!",
    "Hej Verden!",
    "Hallo Wereld!",
    "Hello World!",
    "Tere maailm!",
    "Hei maailma!",
    "Bonjour monde!",
    "Hallo wrâld!",
    "გამარჯობა მსოფლიო!",
    "Hallo Welt!",
    "Γειά σου Κόσμε!",
    "Sannu Duniya!",
    "שלום עולם!",
    "नमस्ते दुनिया!",
    "Helló Világ!",
    "Halló heimur!",
    "Ndewo Ụwa!",
    "Halo Dunia!",
    "Ciao mondo!",
    "こんにちは世界！",
    "Сәлем Әлем!",
    "សួស្តី​ពិភពលោក!",
    "Салам дүйнө!",
    "ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ!",
    "Sveika pasaule!",
    "Labas pasauli!",
    "Moien Welt!",
    "Здраво свету!",
    "Hai dunia!",
    "ഹലോ വേൾഡ്!",
    "Сайн уу дэлхий!",
    "မင်္ဂလာပါကမ္ဘာလောက!",
    "नमस्कार संसार!",
    "Hei Verden!",
    "سلام نړی!",
    "سلام دنیا!",
    "Witaj świecie!",
    "Olá Mundo!",
    "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ!",
    "Salut Lume!",
    "Привет мир!",
    "Hàlo a Shaoghail!",
    "Здраво Свете!",
    "Lefatše Lumela!",
    "හෙලෝ වර්ල්ඩ්!",
    "Pozdravljen svet!",
    "¡Hola Mundo!",
    "Halo Dunya!",
    "Salamu Dunia!",
    "Hej världen!",
    "Салом Ҷаҳон!",
    "สวัสดีชาวโลก!",
    "Selam Dünya!",
    "Привіт Світ!",
    "Salom Dunyo!",
    "Chào thế giới!",
    "Helo Byd!",
    "Molo Lizwe!",
    "העלא וועלט!",
    "Mo ki O Ile Aiye!",
    "Sawubona Mhlaba!",
};

constexpr std::string_view helloWorld_LC[] = {
    "hello wêreld!",
    "përshendetje botë!",
    "ሰላም ልዑል!",
    "مرحبا بالعالم!",
    "բարեւ աշխարհ!",
    "kaixo mundua!",
    "прывітанне сусвет!",
    "ওহে বিশ্ব!",
    "здравей свят!",
    "hola món!",
    "moni dziko lapansi!",
    "你好世界！",
    "pozdrav svijete!",
    "ahoj světe!",
    "hej verden!",
    "hallo wereld!",
    "hello world!",
    "tere maailm!",
    "hei maailma!",
    "bonjour monde!",
    "hallo wrâld!",
    "გამარჯობა მსოფლიო!",
    "hallo welt!",
    "γειά σου κόσμε!",
    "sannu duniya!",
    "שלום עולם!",
    "नमस्ते दुनिया!",
    "helló világ!",
    "halló heimur!",
    "ndewo ụwa!",
    "halo dunia!",
    "ciao mondo!",
    "こんにちは世界！",
    "сәлем әлем!",
    "សួស្តី​ពិភពលោក!",
    "салам дүйнө!",
    "ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ!",
    "sveika pasaule!",
    "labas pasauli!",
    "moien welt!",
    "здраво свету!",
    "hai dunia!",
    "ഹലോ വേൾഡ്!",
    "сайн уу дэлхий!",
    "မင်္ဂလာပါကမ္ဘာလောက!",
    "नमस्कार संसार!",
    "hei verden!",
    "سلام نړی!",
    "سلام دنیا!",
    "witaj świecie!",
    "olá mundo!",
    "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ!",
    "salut lume!",
    "привет мир!",
    "hàlo a shaoghail!",
    "здраво свете!",
    "lefatše lumela!",
    "හෙලෝ වර්ල්ඩ්!",
    "pozdravljen svet!",
    "¡hola mundo!",
    "halo dunya!",
    "salamu dunia!",
    "hej världen!",
    "салом ҷаҳон!",
    "สวัสดีชาวโลก!",
    "selam dünya!",
    "привіт світ!",
    "salom dunyo!",
    "chào thế giới!",
    "helo byd!",
    "molo lizwe!",
    "העלא וועלט!",
    "mo ki o ile aiye!",
    "sawubona mhlaba!",
};

constexpr std::string_view helloWorld_UC[] = {
    "HELLO WÊRELD!",
    "PËRSHENDETJE BOTË!",
    "ሰላም ልዑል!",
    "مرحبا بالعالم!",
    "ԲԱՐԵՒ ԱՇԽԱՐՀ!",
    "KAIXO MUNDUA!",
    "ПРЫВІТАННЕ СУСВЕТ!",
    "ওহে বিশ্ব!",
    "ЗДРАВЕЙ СВЯТ!",
    "HOLA MÓN!",
    "MONI DZIKO LAPANSI!",
    "你好世界！",
    "POZDRAV SVIJETE!",
    "AHOJ SVĚTE!",
    "HEJ VERDEN!",
    "HALLO WERELD!",
    "HELLO WORLD!",
    "TERE MAAILM!",
    "HEI MAAILMA!",
    "BONJOUR MONDE!",
    "HALLO WRÂLD!",
    "ᲒᲐᲛᲐᲠᲯᲝᲑᲐ ᲛᲡᲝᲤᲚᲘᲝ!",
    "HALLO WELT!",
    "ΓΕΙΆ ΣΟΥ ΚΌΣΜΕ!",
    "SANNU DUNIYA!",
    "שלום עולם!",
    "नमस्ते दुनिया!",
    "HELLÓ VILÁG!",
    "HALLÓ HEIMUR!",
    "NDEWO ỤWA!",
    "HALO DUNIA!",
    "CIAO MONDO!",
    "こんにちは世界！",
    "СӘЛЕМ ӘЛЕМ!",
    "សួស្តី​ពិភពលោក!",
    "САЛАМ ДҮЙНӨ!",
    "ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ!",
    "SVEIKA PASAULE!",
    "LABAS PASAULI!",
    "MOIEN WELT!",
    "ЗДРАВО СВЕТУ!",
    "HAI DUNIA!",
    "ഹലോ വേൾഡ്!",
    "САЙН УУ ДЭЛХИЙ!",
    "မင်္ဂလာပါကမ္ဘာလောက!",
    "नमस्कार संसार!",
    "HEI VERDEN!",
    "سلام نړی!",
    "سلام دنیا!",
    "WITAJ ŚWIECIE!",
    "OLÁ MUNDO!",
    "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ!",
    "SALUT LUME!",
    "ПРИВЕТ МИР!",
    "HÀLO A SHAOGHAIL!",
    "ЗДРАВО СВЕТЕ!",
    "LEFATŠE LUMELA!",
    "හෙලෝ වර්ල්ඩ්!",
    "POZDRAVLJEN SVET!",
    "¡HOLA MUNDO!",
    "HALO DUNYA!",
    "SALAMU DUNIA!",
    "HEJ VÄRLDEN!",
    "САЛОМ ҶАҲОН!",
    "สวัสดีชาวโลก!",
    "SELAM DÜNYA!",
    "ПРИВІТ СВІТ!",
    "SALOM DUNYO!",
    "CHÀO THẾ GIỚI!",
    "HELO BYD!",
    "MOLO LIZWE!",
    "העלא וועלט!",
    "MO KI O ILE AIYE!",
    "SAWUBONA MHLABA!",
};
