/*
 * Brisk
 *
 * Cross-platform application framework
 * --------------------------------------------------------------
 *
 * Copyright (C) 2024 Brisk Developers
 *
 * This file is part of the Brisk library.
 *
 * Brisk is dual-licensed under the GNU General Public License, version 2 (GPL-2.0+),
 * and a commercial license. You may use, modify, and distribute this software under
 * the terms of the GPL-2.0+ license if you comply with its conditions.
 *
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <http://www.gnu.org/licenses/>.
 *
 * If you do not wish to be bound by the GPL-2.0+ license, you must purchase a commercial
 * license. For commercial licensing options, please visit: https://brisklib.com
 */
#pragma once

#include <string_view>

namespace Brisk {

constexpr std::string_view loremIpsum =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et "
    "dolore magna aliqua. Leo integer malesuada nunc vel risus commodo viverra. Erat velit scelerisque in "
    "dictum non consectetur a. Condimentum mattis pellentesque id nibh tortor id aliquet lectus. Aliquam ut "
    "porttitor leo a diam. Consequat id porta nibh venenatis cras. Sapien nec sagittis aliquam malesuada "
    "bibendum arcu vitae elementum. Enim facilisis gravida neque convallis a cras. Sed vulputate odio ut "
    "enim blandit volutpat maecenas. Tincidunt id aliquet risus feugiat in ante metus dictum at. Vitae et "
    "leo duis ut diam quam nulla porttitor. Amet porttitor eget dolor morbi non arcu risus quis. Augue neque "
    "gravida in fermentum et sollicitudin ac orci phasellus. Pretium viverra suspendisse potenti nullam ac "
    "tortor vitae purus faucibus. Tempor commodo ullamcorper a lacus vestibulum. Felis eget velit aliquet "
    "sagittis. Sit amet aliquam id diam. Cursus eget nunc scelerisque viverra mauris in aliquam. Sagittis id "
    "consectetur purus ut faucibus pulvinar elementum."
    "\n\n"
    "Non arcu risus quis varius quam quisque id. Quis imperdiet massa tincidunt nunc pulvinar sapien et. "
    "Netus et malesuada fames ac turpis egestas integer eget aliquet. Viverra mauris in aliquam sem "
    "fringilla ut morbi tincidunt. Sed risus pretium quam vulputate. In eu mi bibendum neque egestas congue. "
    "Ut tristique et egestas quis ipsum. Ut porttitor leo a diam sollicitudin. Semper auctor neque vitae "
    "tempus quam pellentesque nec nam aliquam. Vel facilisis volutpat est velit egestas dui id ornare. Et "
    "sollicitudin ac orci phasellus. Sit amet cursus sit amet. Commodo nulla facilisi nullam vehicula ipsum "
    "a arcu. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Ultrices sagittis orci "
    "a scelerisque. Adipiscing tristique risus nec feugiat in fermentum posuere. Adipiscing elit "
    "pellentesque habitant morbi tristique senectus et. Amet commodo nulla facilisi nullam vehicula ipsum a."

    "\n\n"
    "Ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel. Enim ut tellus elementum sagittis "
    "vitae et leo duis. Mauris a diam maecenas sed enim. Ipsum nunc aliquet bibendum enim facilisis gravida. "
    "Ultrices mi tempus imperdiet nulla. Pulvinar pellentesque habitant morbi tristique senectus. Venenatis "
    "a condimentum vitae sapien pellentesque habitant. Magna fermentum iaculis eu non. Mauris pellentesque "
    "pulvinar pellentesque habitant morbi tristique senectus et. Tellus cras adipiscing enim eu turpis "
    "egestas pretium aenean. Sed risus ultricies tristique nulla aliquet enim tortor at."
    "\n\n"
    "In mollis nunc sed id semper risus in. Urna porttitor rhoncus dolor purus non enim. Neque gravida in "
    "fermentum et sollicitudin ac orci phasellus egestas. Ut enim blandit volutpat maecenas volutpat blandit "
    "aliquam etiam erat. Amet est placerat in egestas erat imperdiet sed euismod nisi. Mi tempus imperdiet "
    "nulla malesuada. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus a. Habitant morbi "
    "tristique senectus et netus et malesuada fames ac. Elementum eu facilisis sed odio morbi quis commodo "
    "odio. Pellentesque diam volutpat commodo sed. Egestas tellus rutrum tellus pellentesque. Libero enim "
    "sed faucibus turpis in eu mi bibendum neque. Ac odio tempor orci dapibus. Facilisis sed odio morbi quis "
    "commodo odio aenean sed adipiscing. Neque volutpat ac tincidunt vitae semper quis lectus. Mattis "
    "rhoncus urna neque viverra justo nec. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. "
    "Nam at lectus urna duis convallis convallis tellus id. Dis parturient montes nascetur ridiculus mus."
    "\n\n"
    "Massa eget egestas purus viverra accumsan in nisl. Nam aliquam sem et tortor consequat. Eu sem integer "
    "vitae justo eget magna. Congue nisi vitae suscipit tellus mauris a diam maecenas. Gravida cum sociis "
    "natoque penatibus. Convallis a cras semper auctor neque vitae tempus quam pellentesque. Sed risus "
    "ultricies tristique nulla aliquet enim tortor at. Tempus imperdiet nulla malesuada pellentesque elit "
    "eget gravida. Id interdum velit laoreet id donec ultrices tincidunt arcu. Eu ultrices vitae auctor eu "
    "augue ut lectus arcu bibendum. Iaculis nunc sed augue lacus. Turpis massa sed elementum tempus egestas "
    "sed. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Sed adipiscing diam donec "
    "adipiscing tristique risus nec feugiat. Semper feugiat nibh sed pulvinar proin gravida. Magna sit amet "
    "purus gravida quis blandit turpis cursus. Auctor elit sed vulputate mi. Magnis dis parturient montes "
    "nascetur."
    "\n\n"
    "At tellus at urna condimentum mattis pellentesque id nibh. Elementum facilisis leo vel fringilla. "
    "Lectus proin nibh nisl condimentum id. Tristique risus nec feugiat in fermentum posuere urna nec "
    "tincidunt. Dictum sit amet justo donec enim diam vulputate ut pharetra. Id velit ut tortor pretium "
    "viverra. Gravida neque convallis a cras semper. Pulvinar elementum integer enim neque volutpat ac. "
    "Consectetur libero id faucibus nisl. Platea dictumst quisque sagittis purus sit amet. Sit amet mattis "
    "vulputate enim. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Pharetra convallis "
    "posuere morbi leo urna molestie. Quam viverra orci sagittis eu volutpat. Tempus imperdiet nulla "
    "malesuada pellentesque elit. Non quam lacus suspendisse faucibus interdum posuere lorem. Venenatis cras "
    "sed felis eget."
    "\n\n"
    "Mattis vulputate enim nulla aliquet porttitor lacus. Id donec ultrices tincidunt arcu non sodales "
    "neque. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Pretium fusce id velit "
    "ut. Ultrices eros in cursus turpis massa tincidunt. Sapien nec sagittis aliquam malesuada. Diam ut "
    "venenatis tellus in metus vulputate eu scelerisque. Tellus elementum sagittis vitae et leo duis ut diam "
    "quam. Duis convallis convallis tellus id interdum. In egestas erat imperdiet sed. Justo laoreet sit "
    "amet cursus sit. Lacus sed viverra tellus in hac habitasse platea dictumst. Sit amet nulla facilisi "
    "morbi tempus iaculis urna id volutpat. Suscipit tellus mauris a diam maecenas sed enim ut sem. Sed "
    "libero enim sed faucibus turpis in eu. Enim lobortis scelerisque fermentum dui faucibus in ornare. Cras "
    "fermentum odio eu feugiat pretium nibh ipsum."
    "\n\n"
    "Faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Amet porttitor eget dolor "
    "morbi. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Amet consectetur "
    "adipiscing elit duis tristique. Lorem mollis aliquam ut porttitor. Risus pretium quam vulputate "
    "dignissim suspendisse. Eget velit aliquet sagittis id consectetur purus ut. Euismod lacinia at quis "
    "risus. Lorem ipsum dolor sit amet consectetur adipiscing. Accumsan tortor posuere ac ut consequat "
    "semper viverra nam. Aliquam malesuada bibendum arcu vitae elementum. Et leo duis ut diam quam. Eu "
    "feugiat pretium nibh ipsum consequat nisl. Convallis posuere morbi leo urna molestie at elementum eu. "
    "Sem viverra aliquet eget sit amet tellus cras. Aliquet eget sit amet tellus cras. Vitae congue mauris "
    "rhoncus aenean vel elit scelerisque."
    "\n\n"
    "At ultrices mi tempus imperdiet nulla. Vitae semper quis lectus nulla at volutpat. Justo eget magna "
    "fermentum iaculis eu non diam phasellus vestibulum. Amet cursus sit amet dictum sit amet. Phasellus "
    "faucibus scelerisque eleifend donec pretium vulputate sapien nec. Velit dignissim sodales ut eu sem "
    "integer. Tellus at urna condimentum mattis pellentesque. Porttitor eget dolor morbi non arcu. Nisi quis "
    "eleifend quam adipiscing vitae proin sagittis nisl. Arcu non sodales neque sodales ut. Amet volutpat "
    "consequat mauris nunc congue nisi vitae suscipit. Massa vitae tortor condimentum lacinia quis vel eros "
    "donec ac. Nisi vitae suscipit tellus mauris."
    "\n\n"
    "Risus pretium quam vulputate dignissim suspendisse in est. Ligula ullamcorper malesuada proin libero "
    "nunc consequat interdum varius sit. Blandit libero volutpat sed cras ornare arcu. Vulputate dignissim "
    "suspendisse in est ante in nibh. Faucibus nisl tincidunt eget nullam non nisi. Sit amet mattis "
    "vulputate enim nulla aliquet. Nec dui nunc mattis enim ut tellus elementum sagittis vitae. Quam id leo "
    "in vitae turpis massa sed elementum. Est lorem ipsum dolor sit amet consectetur. Dui vivamus arcu felis "
    "bibendum ut tristique et egestas quis. A condimentum vitae sapien pellentesque habitant morbi "
    "tristique. Et sollicitudin ac orci phasellus egestas tellus. At consectetur lorem donec massa sapien "
    "faucibus. Ultrices in iaculis nunc sed augue."
    "\n\n"
    "Pellentesque massa placerat duis ultricies lacus. Volutpat ac tincidunt vitae semper quis. Mauris "
    "pharetra et ultrices neque ornare aenean euismod elementum. Lacus vel facilisis volutpat est velit. Leo "
    "vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Sit amet nisl suscipit adipiscing "
    "bibendum est ultricies integer. Amet volutpat consequat mauris nunc. Enim neque volutpat ac tincidunt. "
    "Lorem sed risus ultricies tristique nulla aliquet. Non blandit massa enim nec dui nunc mattis enim. "
    "Tempor orci dapibus ultrices in iaculis nunc. Id interdum velit laoreet id. Diam sit amet nisl suscipit "
    "adipiscing bibendum. Aliquam vestibulum morbi blandit cursus risus at ultrices mi."
    "\n\n"
    "Pulvinar proin gravida hendrerit lectus. Sit amet est placerat in egestas erat imperdiet sed. Nunc "
    "consequat interdum varius sit amet mattis vulputate enim nulla. Mauris pellentesque pulvinar "
    "pellentesque habitant morbi. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. "
    "Lacus sed turpis tincidunt id aliquet. Dictum at tempor commodo ullamcorper a lacus. A lacus vestibulum "
    "sed arcu non. Sit amet volutpat consequat mauris. Arcu felis bibendum ut tristique et egestas quis "
    "ipsum. Eu volutpat odio facilisis mauris sit amet. Scelerisque felis imperdiet proin fermentum. "
    "Bibendum ut tristique et egestas."
    "\n\n"
    "Vitae congue eu consequat ac felis donec et. Sed elementum tempus egestas sed sed risus pretium quam. "
    "Sit amet consectetur adipiscing elit. Nunc consequat interdum varius sit amet mattis vulputate enim. "
    "Egestas pretium aenean pharetra magna ac. Blandit massa enim nec dui nunc. Suscipit tellus mauris a "
    "diam maecenas sed enim. Amet facilisis magna etiam tempor orci eu lobortis. Interdum velit euismod in "
    "pellentesque massa. Leo duis ut diam quam nulla porttitor massa id neque. Urna cursus eget nunc "
    "scelerisque viverra mauris. Lectus urna duis convallis convallis tellus id. Velit sed ullamcorper morbi "
    "tincidunt ornare massa eget egestas purus. Ac turpis egestas integer eget aliquet nibh praesent "
    "tristique magna. Vel turpis nunc eget lorem dolor sed viverra. Vulputate eu scelerisque felis imperdiet "
    "proin fermentum. Arcu vitae elementum curabitur vitae nunc sed velit dignissim sodales."
    "\n\n"
    "Aliquam ut porttitor leo a. Quisque egestas diam in arcu cursus. Pretium aenean pharetra magna ac "
    "placerat vestibulum lectus. Purus viverra accumsan in nisl nisi scelerisque eu ultrices vitae. "
    "Pellentesque habitant morbi tristique senectus et netus et malesuada fames. In nibh mauris cursus "
    "mattis molestie a iaculis. At augue eget arcu dictum varius. Sapien pellentesque habitant morbi "
    "tristique senectus et netus et malesuada. Sem integer vitae justo eget magna fermentum. Pulvinar sapien "
    "et ligula ullamcorper malesuada proin. Pellentesque pulvinar pellentesque habitant morbi tristique "
    "senectus et. Euismod in pellentesque massa placerat duis ultricies lacus sed turpis. Aliquet bibendum "
    "enim facilisis gravida neque convallis. Mattis vulputate enim nulla aliquet porttitor. Cras semper "
    "auctor neque vitae tempus quam. A cras semper auctor neque vitae tempus. Risus nec feugiat in "
    "fermentum. Elementum integer enim neque volutpat."
    "\n\n"
    "Mi sit amet mauris commodo quis imperdiet. Mi eget mauris pharetra et ultrices neque ornare. "
    "Consectetur lorem donec massa sapien. Arcu odio ut sem nulla pharetra diam. Egestas pretium aenean "
    "pharetra magna ac placerat vestibulum lectus mauris. Facilisis leo vel fringilla est ullamcorper. "
    "Mattis ullamcorper velit sed ullamcorper morbi. Viverra nibh cras pulvinar mattis nunc sed blandit "
    "libero volutpat. Sed faucibus turpis in eu mi bibendum neque. Purus in mollis nunc sed id semper. Dis "
    "parturient montes nascetur ridiculus. Dolor sit amet consectetur adipiscing elit. Purus ut faucibus "
    "pulvinar elementum integer enim neque volutpat. Nunc faucibus a pellentesque sit amet porttitor eget."
    "\n\n"
    "Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Nullam ac tortor vitae purus "
    "faucibus ornare. Aenean vel elit scelerisque mauris pellentesque pulvinar. Cras pulvinar mattis nunc "
    "sed blandit. A erat nam at lectus urna duis convallis. Risus sed vulputate odio ut enim blandit. Auctor "
    "urna nunc id cursus metus aliquam eleifend mi in. Ridiculus mus mauris vitae ultricies leo integer "
    "malesuada. Ante in nibh mauris cursus mattis molestie a iaculis. Mauris vitae ultricies leo integer "
    "malesuada nunc vel risus. Ac tortor dignissim convallis aenean et tortor at. Scelerisque purus semper "
    "eget duis at tellus. Eu consequat ac felis donec et odio pellentesque diam. Diam vel quam elementum "
    "pulvinar etiam non."
    "\n\n"
    "Quis varius quam quisque id diam. Pulvinar sapien et ligula ullamcorper malesuada proin libero. Mattis "
    "ullamcorper velit sed ullamcorper. Cursus turpis massa tincidunt dui ut ornare lectus. Venenatis a "
    "condimentum vitae sapien pellentesque habitant morbi. Vehicula ipsum a arcu cursus vitae congue. "
    "Aliquet lectus proin nibh nisl condimentum id. At quis risus sed vulputate odio ut enim blandit "
    "volutpat. Eget magna fermentum iaculis eu non diam phasellus vestibulum. Orci phasellus egestas tellus "
    "rutrum tellus pellentesque eu tincidunt tortor. Volutpat blandit aliquam etiam erat velit scelerisque "
    "in. Urna nunc id cursus metus aliquam eleifend mi in nulla. Elit at imperdiet dui accumsan sit amet "
    "nulla. Amet dictum sit amet justo donec enim diam vulputate ut. Ut tellus elementum sagittis vitae et "
    "leo. Imperdiet sed euismod nisi porta lorem. Hendrerit dolor magna eget est lorem. Massa tincidunt dui "
    "ut ornare lectus sit amet est. Id leo in vitae turpis massa sed elementum."
    "\n\n"
    "Tincidunt vitae semper quis lectus nulla at volutpat diam. Faucibus ornare suspendisse sed nisi. "
    "Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Dictumst quisque sagittis purus sit amet "
    "volutpat consequat. Sed turpis tincidunt id aliquet risus feugiat. Orci phasellus egestas tellus "
    "rutrum. Volutpat ac tincidunt vitae semper quis lectus nulla at. Sed turpis tincidunt id aliquet risus. "
    "Amet massa vitae tortor condimentum lacinia quis vel. Nec tincidunt praesent semper feugiat nibh sed "
    "pulvinar proin. Sed tempus urna et pharetra pharetra massa massa ultricies. Sem viverra aliquet eget "
    "sit amet tellus cras adipiscing enim. Amet luctus venenatis lectus magna fringilla."
    "\n\n"
    "Bibendum arcu vitae elementum curabitur vitae nunc sed. Vulputate sapien nec sagittis aliquam malesuada "
    "bibendum. Dignissim convallis aenean et tortor at. Nibh tortor id aliquet lectus. Enim ut sem viverra "
    "aliquet eget sit amet tellus cras. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis "
    "orci. Aliquet nibh praesent tristique magna. Faucibus nisl tincidunt eget nullam non nisi est sit amet. "
    "Eu volutpat odio facilisis mauris sit amet massa vitae tortor. Orci nulla pellentesque dignissim enim "
    "sit amet venenatis. Enim eu turpis egestas pretium. Purus sit amet volutpat consequat mauris nunc "
    "congue nisi. Dui accumsan sit amet nulla facilisi morbi tempus iaculis urna."
    "\n\n"
    "Quis lectus nulla at volutpat diam. Quis eleifend quam adipiscing vitae proin sagittis nisl. Malesuada "
    "proin libero nunc consequat interdum varius sit amet. Ac turpis egestas integer eget aliquet. Et "
    "egestas quis ipsum suspendisse ultrices gravida dictum. Quis ipsum suspendisse ultrices gravida dictum "
    "fusce ut placerat. Morbi tristique senectus et netus et malesuada fames. Placerat orci nulla "
    "pellentesque dignissim enim sit amet. Donec pretium vulputate sapien nec sagittis aliquam malesuada "
    "bibendum arcu. Vitae suscipit tellus mauris a. Malesuada fames ac turpis egestas maecenas pharetra "
    "convallis. Cursus euismod quis viverra nibh. Sed ullamcorper morbi tincidunt ornare massa eget egestas "
    "purus. Aliquam etiam erat velit scelerisque in. Lacus vestibulum sed arcu non odio euismod. Pretium "
    "aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Pellentesque habitant morbi "
    "tristique senectus et. Risus nullam eget felis eget nunc lobortis mattis. Pharetra massa massa "
    "ultricies mi quis hendrerit dolor. Neque gravida in fermentum et sollicitudin ac.";
}
