/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <yoga/enums/YogaEnums.h>

namespace facebook::yoga {

enum class Errata : uint32_t {
  None = 0,
  StretchFlexBasis = 1,
  AbsolutePositioningIncorrect = 2,
  AbsolutePercentAgainstInnerSize = 4,
  All = 2147483647,
  Classic = 2147483646,
};

YG_DEFINE_ENUM_FLAG_OPERATORS(Errata)

const char* toString(Errata e);
} // namespace facebook::yoga
