/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <yoga/enums/YogaEnums.h>

namespace facebook::yoga {

enum class ExperimentalFeature : uint8_t {
  WebFlexBasis,
};

template <>
constexpr int32_t ordinalCount<ExperimentalFeature>() {
  return 1;
}

const char* toString(ExperimentalFeature e);
} // namespace facebook::yoga
