/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <yoga/enums/YogaEnums.h>

namespace facebook::yoga {

enum class FlexDirection : uint8_t {
  Column,
  ColumnReverse,
  Row,
  RowReverse,
};

template <>
constexpr int32_t ordinalCount<FlexDirection>() {
  return 4;
}

const char* toString(FlexDirection e);
} // namespace facebook::yoga
