/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <yoga/enums/YogaEnums.h>

namespace facebook::yoga {

enum class Overflow : uint8_t {
  None,
  AllowRow, // X
  AllowColumn, // Y
  Allow,
};

YG_DEFINE_ENUM_FLAG_OPERATORS(Overflow)

template <>
constexpr int32_t ordinalCount<Overflow>() {
  return 4;
}

const char* toString(Overflow e);
} // namespace facebook::yoga
