/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <yoga/enums/YogaEnums.h>

namespace facebook::yoga {

enum class PositionType : uint8_t {
  Static,
  Relative,
  Absolute,
};

template <>
constexpr int32_t ordinalCount<PositionType>() {
  return 3;
}

const char* toString(PositionType e);
} // namespace facebook::yoga
