/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <yoga/enums/YogaEnums.h>

namespace facebook::yoga {

enum class Unit : uint8_t {
  Undefined,
  Point,
  Percent,
  Auto,
};

template <>
constexpr int32_t ordinalCount<Unit>() {
  return 4;
}

const char* toString(Unit e);
} // namespace facebook::yoga
