set(yogacore_SRC
    ${CMAKE_CURRENT_LIST_DIR}/yoga/Yoga.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/AbsoluteLayout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/AbsoluteLayout.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/Align.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/Baseline.cpp
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/Baseline.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/BoundAxis.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/Cache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/Cache.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/CalculateLayout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/CalculateLayout.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/FlexDirection.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/FlexLine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/FlexLine.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/PixelGrid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/PixelGrid.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/SizingMode.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/algorithm/TrailingPosition.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/config/Config.cpp
    ${CMAKE_CURRENT_LIST_DIR}/yoga/config/Config.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/debug/AssertFatal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/yoga/debug/AssertFatal.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/debug/Log.cpp
    ${CMAKE_CURRENT_LIST_DIR}/yoga/debug/Log.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/Align.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/Dimension.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/Direction.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/Display.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/Edge.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/Errata.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/ExperimentalFeature.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/FlexDirection.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/Gutter.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/Justify.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/LogLevel.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/MeasureMode.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/NodeType.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/Overflow.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/PhysicalEdge.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/PositionType.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/Unit.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/Wrap.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/enums/YogaEnums.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/node/CachedMeasurement.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/node/LayoutResults.cpp
    ${CMAKE_CURRENT_LIST_DIR}/yoga/node/LayoutResults.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/node/Node.cpp
    ${CMAKE_CURRENT_LIST_DIR}/yoga/node/Node.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/numeric/Comparison.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/numeric/FloatOptional.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/style/Style.h
    ${CMAKE_CURRENT_LIST_DIR}/yoga/style/StyleLength.h)
