include($ENV{VCPKG_ROOT}/scripts/toolchains/windows.cmake)

string(REPLACE "/Z7" "" CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}")
string(REPLACE "/Z7" "" CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")

if (DEFINED ENV{LLVM_DIR})

    string(REPLACE "/MP" "" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
    string(REPLACE "/MP" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")

    string(REPLACE "/Z7" "" CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG}")
    string(REPLACE "/Z7" "" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}")

    file(TO_CMAKE_PATH $ENV{LLVM_DIR} LLVM_DIR_FIXED)
    set(CMAKE_C_COMPILER
        "${LLVM_DIR_FIXED}/bin/clang-cl.exe"
        CACHE PATH "" FORCE)
    set(CMAKE_CXX_COMPILER
        "${LLVM_DIR_FIXED}/bin/clang-cl.exe"
        CACHE PATH "" FORCE)
    set(CMAKE_LINKER
        "${LLVM_DIR_FIXED}/bin/lld-link.exe"
        CACHE PATH "" FORCE)
endif ()

set(CMAKE_C_FLAGS
    "${CMAKE_C_FLAGS}"
    CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS
    "${CMAKE_CXX_FLAGS}"
    CACHE STRING "" FORCE)

set(CMAKE_C_FLAGS_RELEASE
    "${CMAKE_C_FLAGS_RELEASE}"
    CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELEASE
    "${CMAKE_CXX_FLAGS_RELEASE}"
    CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_DEBUG
    "${CMAKE_C_FLAGS_DEBUG}"
    CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_DEBUG
    "${CMAKE_CXX_FLAGS_DEBUG}"
    CACHE STRING "" FORCE)
