name: Test

on: 
  push:
    branches:
      - update-deps

env:
  VCPKG_OVERLAY_TRIPLETS: cmake/triplets
  VCPKG_OVERLAY_PORTS: cmake/ports
  AWS_ACCESS_KEY_ID: ${{ secrets.GHBIN_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.GHBIN_SECRET_KEY }}
  AWS_DEFAULT_REGION: fra1
  AWS_ENDPOINT_URL: https://fra1.digitaloceanspaces.com
  AWS_ENDPOINT_URL_S3: https://fra1.digitaloceanspaces.com
  VCPKG_FEATURE_FLAGS: binarycaching
  VCPKG_BINARY_SOURCES: "clear;x-aws,s3://gh-bin/bincache/,readwrite"

jobs:
  ubuntu-x86_64:
    runs-on: ubuntu-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-linux
      VCPKG_DEFAULT_HOST_TRIPLET: x64-linux
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install prerequisites
      run: |        
        sudo apt-get update && sudo apt-get install -y ninja-build mesa-vulkan-drivers vulkan-tools wget xorg-dev libgl-dev libgl1-mesa-dev libvulkan-dev autoconf autoconf-archive libxrandr-dev libxinerama-dev libxcursor-dev mesa-common-dev libx11-xcb-dev
    - name: Vcpkg
      run: |
        vcpkg install --x-install-root vcpkg_installed --x-feature=icu
    - name: Upload Vcpkg dependencies
      run: |
        cmake -E tar cfJ "${{ runner.temp }}/$VCPKG_DEFAULT_TRIPLET.tar.xz" -- vcpkg_installed
        aws s3 cp --acl public-read "${{ runner.temp }}/$VCPKG_DEFAULT_TRIPLET.tar.xz" s3://gh-bin/brisk-deps/

  windows-x86-64:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static-md
      VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static-md
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Vcpkg
      run: |
        vcpkg install --x-install-root vcpkg_installed --x-feature=icu
    - name: Upload Vcpkg dependencies
      run: |
        cmake -E tar cfJ "${{ runner.temp }}/$Env:VCPKG_DEFAULT_TRIPLET.tar.xz" -- vcpkg_installed
        aws s3 cp --acl public-read "${{ runner.temp }}/$Env:VCPKG_DEFAULT_TRIPLET.tar.xz" s3://gh-bin/brisk-deps/

  windows-x86:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x86-windows-static-md
      VCPKG_DEFAULT_HOST_TRIPLET: x86-windows-static-md
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install prerequisites
      run: |
        choco install ninja --no-progress -y
    - name: Vcpkg
      run: |
        vcpkg install --x-install-root vcpkg_installed --x-feature=icu
    - name: Upload Vcpkg dependencies
      run: |
        cmake -E tar cfJ "${{ runner.temp }}/$Env:VCPKG_DEFAULT_TRIPLET.tar.xz" -- vcpkg_installed
        aws s3 cp --acl public-read "${{ runner.temp }}/$Env:VCPKG_DEFAULT_TRIPLET.tar.xz" s3://gh-bin/brisk-deps/

  macos-arm64:
    runs-on: macos-latest
    env:
      VCPKG_DEFAULT_TRIPLET: arm64-osx
      VCPKG_DEFAULT_HOST_TRIPLET: arm64-osx
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install prerequisites
      run: |
        brew install ninja autoconf automake autoconf-archive
        git clone https://github.com/microsoft/vcpkg "$HOME/vcpkg"
    - name: Vcpkg
      run: |
        export VCPKG_ROOT="$HOME/vcpkg"
        $HOME/vcpkg/bootstrap-vcpkg.sh -disableMetrics
        $HOME/vcpkg/vcpkg install --x-install-root vcpkg_installed --x-feature=icu
    - name: Upload Vcpkg dependencies
      run: |
        cmake -E tar cfJ "${{ runner.temp }}/$VCPKG_DEFAULT_TRIPLET.tar.xz" -- vcpkg_installed
        aws s3 cp --acl public-read "${{ runner.temp }}/$VCPKG_DEFAULT_TRIPLET.tar.xz" s3://gh-bin/brisk-deps/

  macos-x86_64:
    runs-on: macos-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-osx
      VCPKG_DEFAULT_HOST_TRIPLET: x64-osx
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install prerequisites
      run: |
        brew install ninja autoconf automake autoconf-archive
        git clone https://github.com/microsoft/vcpkg "$HOME/vcpkg"
    - name: Vcpkg
      run: |
        export VCPKG_ROOT="$HOME/vcpkg"
        $HOME/vcpkg/bootstrap-vcpkg.sh -disableMetrics
        $HOME/vcpkg/vcpkg install --x-install-root vcpkg_installed --x-feature=icu
    - name: Upload Vcpkg dependencies
      run: |
        cmake -E tar cfJ "${{ runner.temp }}/$VCPKG_DEFAULT_TRIPLET.tar.xz" -- vcpkg_installed
        aws s3 cp --acl public-read "${{ runner.temp }}/$VCPKG_DEFAULT_TRIPLET.tar.xz" s3://gh-bin/brisk-deps/
